odinBank/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('users/', include('users.urls')),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.view_login, name='login'),
    path('cadastro/', views.view_cadastro, name='cadastro'),
    path('perfil/', views.view_perfil, name='perfil'),
    path('cliente/<int:cliente_id>/', views.view_cliente_detalhes, name='cliente_detalhes'),
    path('solicitar-credito/', views.solicitar_credito, name='solicitar_credito'),
    path('solicitacoes/', views.lista_solicitacoes_gerente, name='lista_solicitacoes_gerente'),
    path('solicitacoes/<int:solicitacao_id>/', views.responder_solicitacao, name='responder_solicitacao'),
    path('transferencia/', views.transferencia, name="transferencia"),
    path('extrato/', views.extrato, name='extrato'),
    path('cartoes/', views.listar_cartoes, name='listar_cartoes'),    
    path('cartoes/solicitar/<int:cartao_id>/', views.solicitar_cartao, name='solicitar_cartao'),
    path("meus-cartoes/", views.meus_cartoes, name="meus_cartoes"),

    path("gerente/solicitacoes-cartoes/", views.visualizar_solicitacoes_cartoes, name="solicitacoes_cartoes"),
    path(
        "gerente/solicitacoes-cartoes/<int:solicitacao_id>/<str:acao>/",
        views.aprovar_ou_negar_cartao,
        name="aprovar_ou_negar_cartao"
    ),
]

odinBank/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'odinBank/home/index.html')

templates/odinBank/home/index.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OdinBank</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'home/style.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200&icon_names=raven" />
</head>
<body>
    <div class="container">
        <span class="material-symbols-outlined">
            raven
        </span>
        
        <hr>

        <div class="container_children">
            <h1>Bem-vindo ao OdinBank</h1>
            <p class="subTxt">Seu banco digital de confiança!</p>
            <a href="{% url 'users:login' %}" class="butLogin">Fazer Login</a>
            <div class="areaCadastro">
                <p>Ainda não possui conta? </p>
                <a href="{% url 'users:cadastro' %}" class="">Cadastre-se</a>
            </div>
        </div>
    
    </div>
</body>
</html>